### ISSUE TITLE
Guilds of Ravnica

### ISSUE THREAD

**Issue by godbit** [mewmew/playground#12]
Jag föreslår en draft (kanske lite mer avskalad så satsar vi krutet på [advents/jul/nyårs]draften). Guilds of Ravnica ha release 5/10.

- Vad: Gruilds of Ravnica (alternativt Dominaria)
- När: 13,14, 20 eller 21 oktober
- Var: Hagis eller Bergis
- Vilka: Skicka doodle till standard, om vissa inte kan så kör vi ändå
    - Ok att köra lite alts, typ Bradley etc. Jag har en snubbe på jobbet som är taggad som jag tror skulle funka bra med övriga gänget också :)

Ville bara kolla att det funkar med/er om ni är taggade? @mewmew @karlek

**Comment by karlek** [comment]
Taggad och 13, 14 fungerar för mig annars är det rätt tätt inpå tentorna.

**Comment by karlek** [comment]
Är upptagen 9-15 på söndag så antingen kör vi lördagen eller en sen på söndagen

**Comment by godbit** [comment]
Aight, då känns ju lördagen som ett bättre rent spontant men vi kan invänta svar från mew. Ifs om man inte ska drafta lika seriöst med prepp osv så blir det ju som en eftermiddag med sällskapsspel och middag egenligen liksom så det borde funka även på söndagen även om det blir mindre spel :)

**Comment by mewmew** [comment]
Låter bra som en initial invite. Kommer ni på någon mer, så kör såklart. En lite mindre formell draft (tycker fortfarande det vore kul att preppa :)) så kör vi oavsett hur många som i slutändan kan.

**Comment by karlek** [comment]
Vi kör på det, lite jobbigt om alla tackar ja 😅

**Comment by godbit** [comment]
Fattade fel, söndagen funkar också!

**Comment by mewmew** [comment]
Trodde Henry hade black biz på söndag.

**Comment by karlek** [comment]
Vi pratar om söndagen den 14:e oktober

**Comment by mewmew** [comment]
> To clarify: Vi pratar om söndagen den 14:e oktober

I know. Var det bara eftermiddag den 14:e (re: https://github.com/mewmew/playground/issues/12#issuecomment-420256626)?

**Comment by godbit** [comment]
Både den 13e och 14e är jag och tanken ledig hela dagen :)

**Comment by godbit** [comment]
Stänger till förmån för officiella repot 😎
