### ISSUE TITLE
Awsome couch table 

### ISSUE THREAD

**Issue by draftlord** [mewmew/playground#4]
Hör av dig till denna snubba så fort du kan imorn, vi kan köra pickup på kvällen tis, ons, tors och fredag. Fråga om den finns kvar och pitach 800 kr(?)

https://www.blocket.se/stockholm/Soffbord_74851797.htm?ca=11&w=1

**Comment by mewmew** [comment]
The awesome couch table has now been implemented and made available in the living room.
