### ISSUE TITLE
Hackathon #1

### ISSUE THREAD

**Issue by godbit** [mewmew/playground#7]
Yo skulle du vara sugen på att köra ett hackathon någon eller flera av dagarna nästa vecka? :) Jag kan onsdag 21/3, torsdag 22/3 eller fredag 23/3. Tänkte typ att man pumpar från morgon till kväll ;)

Tänkte köra lite ML på exjobbet och lite wurst 😎

**Comment by mewmew** [comment]
Lätt! Jag har helt fri dag på tors, så kör lätt då! Har föreläsningar och Studs de andra dagarna.

Föreslår att vi ses ons kväll, preppar middag tillsammans, kanske en bastu? Så kan vi börja hacka loss och sen ha hela torsdagen för random kodande å så!

Hur låter det?

**Comment by godbit** [comment]
Det låter helt perfekt 😍  Ses ons kväll! Grymt med bastu också

**Comment by mewmew** [comment]
> Det låter helt perfekt heart_eyes Ses ons kväll! Grymt med bastu också

Härligt! Bastun är nu bokad <('_'<)

**Comment by godbit** [comment]
:1st_place_medal: 

Jag kom på att vi eventuellt skulle kunna klättra innan om du är sugen(?)
