### ISSUE TITLE
Draft 

### ISSUE THREAD

**Issue by godbit** [mewmew/playground#8]
Känner att det är dags att styra en draft! 😍 

Tänkbara sets:
* Dominaria
  * https://magic.wizards.com/en/products/dominaria
* Battlebond _(release 8 juni)_
  * https://magic.wizards.com/en/products/Battlebond

Förslag på datum:
**26 maj** (lördag)
**6 juni** (nationaldagen ledigt)
**9 juni** (lördag)

Vad sägs?

**Comment by godbit** [comment]
Ping på denna :innocent:  Vore nice att få till något innan du studsar iväg!

**Comment by mewmew** [comment]
Absolut!! Ska vi höras av per telefon imorn och snacka ihop oss :)

**Comment by godbit** [comment]
Låter grymt! Jag ringer ikväll då?

**Comment by godbit** [comment]
https://doodle.com/poll/98r3yagaqpmrvk6v

**Comment by godbit** [comment]
Ping, inte kommit in några svar än. Vore skönt om vi kunde spika ett datum så vi kan låsa in det ;)

**Comment by mewmew** [comment]
@godbit Har nu skrivit upp de datum som jag kan. Skickade länken till Honke, Micke, Danne och Rex. Får *pinga* dom lite mer :)

Kommer bli riktigt kul med en draft! Tack för att du pushar lite! För min del känns det välbehövt med en paus och lite random tid att umgås, så jag är taggad!

Jag gör ett försök under helgen att få tag i resten av gänget.

*kram* <3

**Comment by mewmew** [comment]
Micke kan 5:e, ej 26:e dock.

Ska vi köra 5:e som mål för draften? De som kan kan, och så kör vi!

**Comment by godbit** [comment]
https://www.youtube.com/watch?v=WddpRmmAYkg

**Comment by mewmew** [comment]
http://brain.fm

**Comment by godbit** [comment]
Lägger en liten update på hur vi ligger till. Kommer uppdateras när vi gör progress ;) 

Lösningar/förslag kan refas till Num.

Num |TODO | Status
------------ |------------ | ------------
1 | Köpa boosters | ✔️ 
2 | Fixa inslagning till boosters | -
2a | Papper | -
2b | Snöre | -
3 | Skriva ut Dominaria mechanics | Emil fixar 
4 | Skriva ut Dominaria draft archetypes | Emil fixar
5 | Bestämma mat | -

**Comment by godbit** [comment]
Har formaterat och skrivit ut både mechanics och archetypes nu så tror det blir riktigt nice! Vi behöver bara göra se de ser gamla ut i hagis :)

Ang 2a så funkar det ju med vanligt a4-papper till en skrivare om man gör så det ser gammalt ut. I så fall behöver du bara fixa ett schysst snöre.

**Comment by godbit** [comment]
Preppar papper: https://imgur.com/gallery/U7PgpkW

Fortsätter med vår enda fungerande kommunikationskanal xD

**Comment by mewmew** [comment]
Updated 2b in https://github.com/mewmew/playground/issues/8#issuecomment-386077252

**Comment by mewmew** [comment]
>  Vi behöver bara göra se de ser gamla ut i hagis :)

Lätt. Ugn med citron? Blir lite brunare papper då.

**Comment by mewmew** [comment]
Ref 5. Micke föreslog vi kunde grilla på kvällen eftersom det kommer bli fint väder. Så köra det istället för tacos förslagsvis ;) Breaking one tradition to start another.

**Comment by godbit** [comment]
(2a, 3,  4) Gjorde kaffepapper och torkade med dammsugaren i badrummet 🤣 Funkade skitbra så vi behöver bara göra samma för lite wrapping paper till 2a.

Grillning låter som en grej! Kanske blir tacos till lunch ev men det tar vi ikväll ;)

**Comment by godbit** [comment]
Ny issue kommer inför nästa draft. Vila i frid ❤️
