### ISSUE TITLE
Sairai draft

### ISSUE THREAD

**Issue by godbit** [mewmew/playground#9]
Yello,

Tänkte bara kolla när du kommer till Stockholm på fredag? Ifall vi handlar tillsammans eller om jag ska fixa det så preppar vi bara tillsammans.

----

Sen så lägger jag en progress/TODO likt förra gången

Num |TODO | Status
------------ |------------ | ------------
1 | Köpa boosters | ✔️ 
2a | Fixa rispapper till boosters | Henry :earth_asia: 
2b | Accessoar utöver papper?  | Knajii :sa: + ev något
3 | Rökelse | :heavy_check_mark: 
4 | Skriva draft archetypes | :heavy_check_mark: 
5a | Bestämma lunch | Prel - Yakiniku
5b | Bestämma middag | Japansk tacos :mexico: 
6 | Kontakta Daniel ang tallrikar | -

**Comment by godbit** [comment]
Skickar till @karlek på messenger så han ser och kan komma med input också :)

**Comment by karlek** [comment]
Jag fixar [**3**] idag och kan köpa rispapper om jag får directions till en specifik butik [**2a**].

Middag kanske vi kör japansk/mex-fusion. Vi tänkte Teriyaki kyckling med wasabimajonäs i tortillia.

Lunch skulle kunna vara japansk curry, ramen/soba, fusion-maki, etc.

**Comment by godbit** [comment]
Sweet, tror du får googla lite på rispapper. Jag hittade det inte på panduro :disappointed: 

Har lagt in middagen som spik och ändrat lite statusar. Har du någon idé på 2b @karlek ?

**Comment by godbit** [comment]
2b förslag: Ett indivduellt (valt av tank :tanabata_tree: ) kanjii på varje pack ritat i svart tusch. Kul om kanjiit har en bra mening också. Kanske något litet band eller konstblomma eller något, beroende på hur cleant man vill ha det.

**Comment by karlek** [comment]
Kan svänga förbi en panduro-hobby och se om de har något inspo till 2b

**Comment by godbit** [comment]
Förslag på stil för kanji:
- Vis man
- Hal som en ål
- Apprentice
- Man som gillar nudlar
- Son av tiger
- Tvätthink
- Master swordsmith

Muppig gramatik men ni fattar vad jag menar, några "coola" och några muppiga. Tänker att sensei skulle assignas på denna task?

**Comment by karlek** [comment]
Väldigt sällan har komplexa uttryck som "vis man" ett tecken, utan då består det av två (eller fler). Ibland kan tecken betyda ett ord, men ibland används de bara i ord. Skickar med på en sida med samtliga tecken och väljer ut några.

http://www.manythings.org/kanji/d/index.html

* Hink = 桶
* Ål = 鰻
* Nudlar = 麺
* Roder = 舵
* Chrysanthemum (Kejsarfamiljens egna blomma) = 菊
* Böna = 豆
* Buddistisk präst = 僧
* Skelettben =  骨

**Comment by godbit** [comment]
Sweet, danke! Är ju inte heller otänkbart att det är två kanji likt:
https://thumbs.imagekind.com/frames/92bd32ec-4a4a-4d4c-b7a4-1461deb9b7f4/123/The-Kanji-Meiyo-or-Honor--In-Gyosho_art.jpg?v=1523712119&maxHeight=200

Vi får ta oss en funderare när vi sätter oss och fixar det

**Comment by godbit** [comment]
Det känns som att den lättaste lunchen att preppa vore något i stil med yakiniku/curry som man äter med ris. Då kan man laga mat dagen innan och bara värma på den liksom.

Lägger till en till punkt som är att låna tallrikar av Daniel eftersom vi bara har 5-6 st :sweat_smile:

**Comment by mewmew** [comment]
> Det känns som att den lättaste lunchen att preppa vore något i stil med yakiniku/curry som man äter med ris. Då kan man laga mat dagen innan och bara värma på den liksom.

Jag är lätt på på Yakiniku :)

**Comment by mewmew** [comment]
Jag har med de Japanska boosters'arna i packningen till Finland, så kommer direkt till er på fre!

**Comment by godbit** [comment]
Sweet, jag är också sjukt taggad :heart_eyes: 

Ska kolla lite på yakiniku-recept för å se om det verkar rimligt. Lägger en prel på det i comment 1.

**Comment by mewmew** [comment]
Well fought.

Fick höra från Linda här om dagen att hon verkligen uppskattade de Japanska samuraipyjamasarna från draften, då klädesplagget tydligen fyller dubbel funktion av att vara skönt att ha på sig när en är gravid :)

Stänger denna issue, i inväntan på nästa draft-prep! Vi får ta och prata ihop oss @godbit och @karlek så vi kan få ett riktigt grymt tema till nästa draft :)

**Comment by godbit** [comment]
Haha härligt :)

Yes, nästa set släpps ju väldigt snart så det kanske är lite tidigt att hoppa på det direkt. Dock så har vi ju 8 st Dominaria boosters som vi skulle kunna använda. Om vi köper 4 till så har vi en minidraft för 4 pers som man kan fra på någon vardagskväll :)
